from dataclasses import dataclass
from enum import Enum
from typing import Any


class FaultType(str, Enum):
    PLAN_MISSING_STEP = "PLAN_MISSING_STEP"
    PLAN_INCORRECT_SUCCESS_CRITERIA = "PLAN_INCORRECT_SUCCESS_CRITERIA"
    PLAN_INVALID_DEPENDENCY = "PLAN_INVALID_DEPENDENCY"

    TOOL_WRONG_TOOL = "TOOL_WRONG_TOOL"
    TOOL_WRONG_ARGUMENT = "TOOL_WRONG_ARGUMENT"
    TOOL_UNNECESSARY_CALL = "TOOL_UNNECESSARY_CALL"
    TOOL_FAILED_RECOVERY = "TOOL_FAILED_RECOVERY"

    KNOW_RETRIEVAL_FAILURE = "KNOW_RETRIEVAL_FAILURE"
    KNOW_CITATION_MISMATCH = "KNOW_CITATION_MISMATCH"
    KNOW_CONTEXT_TRUNCATION = "KNOW_CONTEXT_TRUNCATION"

    MA_INCORRECT_HANDOFF = "MA_INCORRECT_HANDOFF"
    MA_INFORMATION_LOSS = "MA_INFORMATION_LOSS"
    MA_MISSING_RESPONSIBILITY = "MA_MISSING_RESPONSIBILITY"
    MA_ROLE_OVERLAP = "MA_ROLE_OVERLAP"

    CTRL_LOOP = "CTRL_LOOP"
    CTRL_PREMATURE_TERMINATION = "CTRL_PREMATURE_TERMINATION"
    CTRL_EXCESSIVE_EXPLORATION = "CTRL_EXCESSIVE_EXPLORATION"

    SEC_PROMPT_INJECTION = "SEC_PROMPT_INJECTION"
    SEC_UNAUTHORIZED_ACTION = "SEC_UNAUTHORIZED_ACTION"
    SEC_CROSS_USER_DATA_LEAKAGE = "SEC_CROSS_USER_DATA_LEAKAGE"


@dataclass
class Fault:
    fault_type: FaultType
    step: int
    parameters: dict[str, Any]
    seed: int | None = None
